const elements={mainControlBtn:null,controlMenu:null,themeBtn:null,homeBtn:null,progressBar:null,backToTop:null,html:document.documentElement};const state={theme:"light",scrollPosition:0,menuOpen:!1,isRestoring:!1};function initTheme(){const savedTheme=localStorage.getItem("user-theme");if(savedTheme){state.theme=savedTheme}else{state.theme=window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}
setTheme(state.theme)}
function setTheme(theme){state.theme=theme;elements.html.setAttribute("data-theme",theme);try{localStorage.setItem("user-theme",theme)}catch(e){}
if(elements.themeBtn)elements.themeBtn.textContent=theme==="dark"?"☀️":"🌙"}
function getScrollEl(){return document.scrollingElement||document.documentElement||document.body}
function computeMaxScroll(){const scrollEl=getScrollEl();const doc=document.documentElement;const body=document.body;const scrollHeight=Math.max(doc.scrollHeight||0,body.scrollHeight||0,scrollEl.scrollHeight||0);const max=Math.max(0,scrollHeight-window.innerHeight);return max}
let scrollTicking=!1;function handleScroll(){if(scrollTicking)return;scrollTicking=!0;requestAnimationFrame(()=>{const scrollEl=getScrollEl();const scrollY=Math.max(0,Math.floor(scrollEl.scrollTop||window.scrollY||0));state.scrollPosition=scrollY;const maxHeight=computeMaxScroll();if(maxHeight>0&&elements.progressBar){let pct=(scrollY/maxHeight)*100;pct=Math.max(0,Math.min(100,pct));elements.progressBar.style.width=pct+"%"}else if(elements.progressBar){elements.progressBar.style.width="0%"}
if(elements.backToTop){elements.backToTop.classList.toggle("show",scrollY>500)}
scrollTicking=!1})}
const bookKey="progress_"+(location.pathname.split("/").pop()||"default");let scrollSaveTimer;function saveScrollPosition(){if(state.isRestoring)return;try{const scrollEl=getScrollEl();const scrollY=scrollEl.scrollTop||window.scrollY||0;const maxScroll=computeMaxScroll();const percentage=maxScroll>0?(scrollY/maxScroll)*100:0;const data={position:Math.floor(scrollY),percentage:percentage,maxScroll:maxScroll,timestamp:Date.now()};localStorage.setItem(bookKey,JSON.stringify(data))}catch(e){}}
function restoreScrollPosition(){try{const savedData=localStorage.getItem(bookKey);if(!savedData)return;const data=JSON.parse(savedData);if(!data||typeof data.position!=='number')return;state.isRestoring=!0;const currentMaxScroll=computeMaxScroll();const layoutChanged=Math.abs(currentMaxScroll-(data.maxScroll||0))>100;let targetPosition=data.position;if(layoutChanged&&data.percentage){targetPosition=(data.percentage/100)*currentMaxScroll}
window.scrollTo({top:targetPosition,behavior:'instant'});setTimeout(()=>{state.isRestoring=!1},800)}catch(e){state.isRestoring=!1}}
function createUIElements(){if(document.getElementById('progressBarContainer'))return;const fragment=document.createDocumentFragment();const progressBarContainer=document.createElement('div');progressBarContainer.id='progressBarContainer';progressBarContainer.innerHTML='<div id="progressBar" aria-hidden="true"></div>';fragment.appendChild(progressBarContainer);const floatingControls=document.createElement('div');floatingControls.className='floating-controls';floatingControls.innerHTML=`
    <button class="control-btn" id="mainControlBtn" aria-label="Menu">☰</button>
    <div class="control-menu" id="controlMenu" aria-hidden="true">
      <button class="control-item" id="homeBtn" aria-label="Home">🏠</button>
      <button class="control-item" id="themeBtn" aria-label="Toggle Theme">🌙</button>
    </div>
  `;fragment.appendChild(floatingControls);const backToTop=document.createElement('button');backToTop.id='backToTop';backToTop.setAttribute('aria-label','Back to Top');backToTop.textContent='↑';fragment.appendChild(backToTop);document.body.insertBefore(fragment,document.body.firstChild)}
function setupEventDelegation(){document.addEventListener("click",(e)=>{const btn=e.target.closest("button");if(!e.target.closest(".floating-controls")&&state.menuOpen){state.menuOpen=!1;if(elements.controlMenu)elements.controlMenu.classList.remove("open");}
if(!btn)return;switch(btn.id){case "mainControlBtn":state.menuOpen=!state.menuOpen;if(elements.controlMenu)elements.controlMenu.classList.toggle("open",state.menuOpen);break;case "themeBtn":setTheme(state.theme==="dark"?"light":"dark");break;case "homeBtn":window.location.href="../index.html";break;case "backToTop":window.scrollTo({top:0,behavior:"smooth"});break}});document.addEventListener("click",(e)=>{const link=e.target.closest("a[href^='#']");if(!link)return;e.preventDefault();const target=document.querySelector(link.getAttribute("href"));if(target){target.scrollIntoView({behavior:"smooth"})}})}
function setupScrollSaving(){let lastScroll=0;window.addEventListener("scroll",()=>{handleScroll();const currentScroll=window.scrollY||document.documentElement.scrollTop||0;if(Math.abs(currentScroll-lastScroll)>10){lastScroll=currentScroll;clearTimeout(scrollSaveTimer);scrollSaveTimer=setTimeout(saveScrollPosition,300)}},{passive:!0});document.addEventListener("visibilitychange",()=>{if(document.hidden){saveScrollPosition()}});window.addEventListener("beforeunload",saveScrollPosition)}
function init(){createUIElements();elements.mainControlBtn=document.getElementById("mainControlBtn");elements.controlMenu=document.getElementById("controlMenu");elements.themeBtn=document.getElementById("themeBtn");elements.homeBtn=document.getElementById("homeBtn");elements.progressBar=document.getElementById("progressBar");elements.backToTop=document.getElementById("backToTop");initTheme();restoreScrollPosition();let ro;try{ro=new ResizeObserver(()=>{if(!state.isRestoring){handleScroll()}});ro.observe(document.body)}catch(e){window.addEventListener('resize',()=>{if(!state.isRestoring){handleScroll()}},{passive:!0})}
setupEventDelegation();setupScrollSaving();handleScroll();window.addEventListener("load",()=>{handleScroll();setTimeout(()=>{restoreScrollPosition()},50)});if(document.fonts&&document.fonts.ready){document.fonts.ready.then(()=>{handleScroll();setTimeout(()=>{restoreScrollPosition()},50)}).catch(()=>{})}}
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",init)}else{init()}