let allBooks=[];let filteredBooks=[];let favorites=[];let renderedCount=0;const ITEMS_PER_PAGE=12;let currentFilter='all';const init=async()=>{loadStorage();setupEventListeners();await fetchBooks()};const fetchBooks=async()=>{const grid=document.getElementById('booksGrid');try{const controller=new AbortController();const timeoutId=setTimeout(()=>controller.abort(),5000);const response=await fetch('books.json',{signal:controller.signal,headers:{'Accept':'application/json'}});clearTimeout(timeoutId);if(!response.ok)throw new Error('Failed to load books');allBooks=await response.json();filteredBooks=[...allBooks];requestAnimationFrame(()=>{resetAndRender()})}catch(error){console.error(error);grid.innerHTML='<div class="error">⚠️ Could not load books. Please refresh.</div>'}};const loadStorage=()=>{try{const storedFavs=localStorage.getItem('aklatell_favorites');if(storedFavs)favorites=JSON.parse(storedFavs);const storedTheme=localStorage.getItem('aklatell_theme');if(storedTheme==='dark'){document.body.classList.add('dark-mode');document.getElementById('themeToggle').textContent='☀️'}}catch(e){console.error('Storage error:',e)}
updateFavCount()};const renderBatch=()=>{const grid=document.getElementById('booksGrid');const loadMoreBtn=document.getElementById('loadMoreBtn');const loading=grid.querySelector('.loading');if(loading)loading.remove();const fragment=document.createDocumentFragment();const nextBatch=filteredBooks.slice(renderedCount,renderedCount+ITEMS_PER_PAGE);if(nextBatch.length===0&&renderedCount===0){grid.innerHTML='<div class="no-results">📖 – No books found.</div>';loadMoreBtn.style.display='none';return}
nextBatch.forEach(book=>{const isFav=favorites.includes(book.id);const card=document.createElement('article');card.className='book-card';card.innerHTML=`
      <a href="${book.link}" class="card-link-overlay" aria-label="Read ${escapeHtml(book.title)}"></a>
      <button class="favorite-btn ${isFav ? 'active' : ''}" 
              data-id="${book.id}"
              aria-label="${isFav ? 'Remove from favorites' : 'Add to favorites'}">
        ${isFav ? '❤️' : '🤍'}
      </button>
      <span class="book-emoji">${book.emoji}</span>
      <h3 class="book-title">${escapeHtml(book.title)}</h3>
      <p class="book-author">by ${escapeHtml(book.author)}</p>
      <p class="book-preview">${escapeHtml(book.preview)}</p>
    `;fragment.appendChild(card)});requestAnimationFrame(()=>{grid.appendChild(fragment);renderedCount+=nextBatch.length;if(renderedCount>=filteredBooks.length){loadMoreBtn.style.display='none'}else{loadMoreBtn.style.display='block'}})};const escapeHtml=(text)=>{const div=document.createElement('div');div.textContent=text;return div.innerHTML};const resetAndRender=()=>{const grid=document.getElementById('booksGrid');grid.innerHTML='';renderedCount=0;renderBatch()};const applyFilters=(searchTerm)=>{let result=allBooks;if(currentFilter==='favorites'){result=result.filter(b=>favorites.includes(b.id))}
if(searchTerm){const lowerSearch=searchTerm.toLowerCase();result=result.filter(b=>b.title.toLowerCase().includes(lowerSearch)||b.author.toLowerCase().includes(lowerSearch))}
const sortBy=document.getElementById('sortSelect').value;if(sortBy==='title'){result.sort((a,b)=>a.title.localeCompare(b.title))}else if(sortBy==='author'){result.sort((a,b)=>a.author.localeCompare(b.author))}else if(sortBy==='newest'){result.sort((a,b)=>b.id-a.id)}
filteredBooks=result;resetAndRender()};const setupEventListeners=()=>{document.getElementById('loadMoreBtn').addEventListener('click',renderBatch,{passive:!0});let searchTimeout;document.getElementById('searchInput').addEventListener('input',(e)=>{clearTimeout(searchTimeout);searchTimeout=setTimeout(()=>{applyFilters(e.target.value.toLowerCase())},300)},{passive:!0});document.getElementById('sortSelect').addEventListener('change',()=>{applyFilters(document.getElementById('searchInput').value.toLowerCase())});document.querySelector('.toolbar-actions').addEventListener('click',(e)=>{if(e.target.classList.contains('filter-chip')){document.querySelectorAll('.filter-chip').forEach(chip=>{chip.classList.remove('active')});e.target.classList.add('active');currentFilter=e.target.dataset.filter;applyFilters(document.getElementById('searchInput').value.toLowerCase())}},{passive:!0});document.getElementById('booksGrid').addEventListener('click',(e)=>{const btn=e.target.closest('.favorite-btn');if(btn){e.preventDefault();e.stopPropagation();const bookId=parseInt(btn.dataset.id);toggleFavorite(bookId);const isFav=favorites.includes(bookId);requestAnimationFrame(()=>{btn.classList.toggle('active',isFav);btn.textContent=isFav?'❤️':'🤍';btn.setAttribute('aria-label',isFav?'Remove from favorites':'Add to favorites')})}});document.getElementById('themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark-mode');const isDark=document.body.classList.contains('dark-mode');requestAnimationFrame(()=>{document.getElementById('themeToggle').textContent=isDark?'☀️':'🌙'});setTimeout(()=>{localStorage.setItem('aklatell_theme',isDark?'dark':'light')},100)},{passive:!0});const menuModal=document.getElementById('menuModal');document.getElementById('menuBtn').addEventListener('click',()=>{requestAnimationFrame(()=>{menuModal.classList.add('active')})},{passive:!0});document.getElementById('closeModal').addEventListener('click',()=>{requestAnimationFrame(()=>{menuModal.classList.remove('active')})},{passive:!0});menuModal.addEventListener('click',(e)=>{if(e.target===menuModal){requestAnimationFrame(()=>{menuModal.classList.remove('active')})}},{passive:!0})};let storageTimeout;const toggleFavorite=(id)=>{const index=favorites.indexOf(id);if(index===-1){favorites.push(id)}else{favorites.splice(index,1)}
clearTimeout(storageTimeout);storageTimeout=setTimeout(()=>{localStorage.setItem('aklatell_favorites',JSON.stringify(favorites))},100);updateFavCount();if(currentFilter==='favorites'){applyFilters(document.getElementById('searchInput').value.toLowerCase())}};const updateFavCount=()=>{requestAnimationFrame(()=>{document.getElementById('favCount').textContent=favorites.length})};if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init)}else{init()}